service: authorization-service
plugins:
  - serverless-dotenv-plugin
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
functions:
  basicAuthorizer:
    handler: basicAuthorizer.handler
resources:
  Outputs:
    authorizationArn:
      Value: arn:aws:lambda:us-east-1:887240492441:function:authorization-service-dev-basicAuthorizer